### ISSUE TITLE
setup middleware project structure

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/fiber-middleware#1]
each project has a structure, and therefore fiber-middleware should have a structure as well for the first step.

Do the following
- setup a project structure that can be used to develop the middleware
- add a sample directory that relies on locally located middleware and a simple fiber-based application.

**Comment by aniketbiswas21** [comment]
@YashKumarVerma Sir, can you add a README in this repo. I am not able to fork as of now. I have written the code.

**Comment by YashKumarVerma** [comment]
the valid levels for gsoc are level 0,1,2 and 3. therefore changing level4 to 3.
